language: java
jdk:
  - oraclejdk8
script:
    - chmod +x travis-build.sh && ./travis-build.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
+
